title: "Ibad Desmukh"
description: "" # Replace with a more specific description

# Jekyll configuration
baseurl: "" # Keep empty for project root URL
url: "https://idesmukh.github.io" 

# Theme configuration (replace with your chosen theme)
theme: minima

# Plugins (optional)
plugins: []

# Collections (optional for managing content)
collections: []

